baseURL = 'https://lrme.sh/'
languageCode = 'en-us'
title = 'lrme.sh'

[module]
  [[module.imports]]
    path = 'github.com/McShelby/hugo-theme-relearn'

[params]
  disableLandingPageButton = false
  search.disable = true
  search.index.disable = true
  search.page.disable = true
  disableShortcutsTitle = true
  themeVariant = 'lrmesh'

[menus]
  [[menus.shortcuts]]
    name = 'Neighbors'

  [[menus.shortcuts]]
    name = '<i class="fa-solid fa-book"></i> Memphis Mesh'
    url = 'http://memphismesh.com/'
    parent = 'Neighbors'
    weight = 10

  [[menus.shortcuts]]
    name = '<i class="fa-solid fa-book"></i> NWA Mesh'
    url = 'https://nwame.sh/'
    parent = 'Neighbors'
    weight = 20

  [[menus.shortcuts]]
    name = '<i class="fa-solid fa-book"></i> Hot Springs Mesh'
    url = 'https://hotme.sh/'
    parent = 'Neighbors'
    weight = 30

  [[menus.shortcuts]]
    name = 'Shortcuts'

  [[menus.shortcuts]]
    name = '<i class="fa-solid fa-map"></i> Public Mesh Map'
    url = 'https://meshmap.net/'
    parent = 'Shortcuts'
    weight = 10

  [[menus.shortcuts]]
    name = '<i class="fa-solid fa-book"></i> Meshtastic Docs'
    url = 'https://meshtastic.org/docs/getting-started/'
    parent = 'Shortcuts'
    weight = 20

  [[menus.shortcuts]]
    name = '<i class="fa-brands fa-discord"></i> Discord'
    url = 'https://discord.gg/meshtastic'
    parent = 'Shortcuts'
    weight = 30

  [[menus.shortcuts]]
    name = '<i class="fa-brands fa-github"></i> lrmesh GitHub Repos'
    url = 'https://github.com/lrmesh'
    parent = 'Shortcuts'
    weight = 40

[[sidebarmenus]]
  disableTitle = true
  identifier = 'home'
  main = true
  pageRef = ''
  type = 'page'

[[sidebarmenus]]
  disableTitle = false
  identifier = 'shortcuts'
  main = false
  type = 'menu'
